<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <!-- Title -->
        <?php echo $this->headTitle($this->translate('5000s.org Magazine'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- Meta -->
        <?php echo $this->headMeta()
            ->setCharset('UTF-8')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0')
            ->appendName('description', '5000s.org Modern Lifestyle with Buddhist Thought Magazine')
            ->appendName('author', 'KBO IT Development')
            ->appendName('robots', 'noindex, nofollow')
            ->appendName('apple-mobile-web-app-capable', 'yes')
            ->appendName('apple-mobile-web-app-status-bar-style', 'black')                
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
    
        <!-- Favicon and CSS -->
        <?php echo $this->headLink(array(
            'rel'   => 'icon',
            'href'  => $this->basePath('assets/images/5000s-favicon.png')))
            ->offsetSetStylesheet(1, $this->basePath('assets/bootstrap/3.3.6/css/bootstrap.min.css')) 
            ->offsetSetStylesheet(2, $this->basePath('assets/bootstrap/3.3.6/css/bootstrap-theme.min.css'))			
            ->offsetSetStylesheet(3, $this->basePath('assets/jquery-ui/1.11.4/jquery-ui.css'))
            ->offsetSetStylesheet(4, $this->basePath('assets/jquery-ui/1.11.4/jquery-ui.structure.css')) 
            ->offsetSetStylesheet(5, $this->basePath('assets/jquery-ui/1.11.4/jquery-ui.theme.css')) 
            ->offsetSetStylesheet(6, $this->basePath('assets/custom/css/kboapp-style.css'))
            ->offsetSetStylesheet(7, $this->basePath('assets/custom/css/kboapp-footer.css'))
        ?>

    </head>
    <body>
	<!-- Navigation Bar -->
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                        <span class="glyphicon glyphicon-home kboapp-color" aria-hidden="true"></span>
                        &nbsp;<?php echo $this->translate('5000s.org Magazine') ?>
                    </a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <form class="navbar-form navbar-right">
                        <div class="form-group">
                            <input type="text" placeholder="Email" class="form-control">
                        </div>
                        <div class="form-group">
                            <input type="password" placeholder="Password" class="form-control">
                        </div>
                        <button type="submit" class="btn btn-success">Sign in</button>
                    </form>
                </div><!-- /.navbar-collapse -->
            </div>
        </nav>        

	<!-- Content -->
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->

	<!-- Footer -->
        <footer class="footer">
            <div class="container">
                <!-- <p class="pull-right"><a href="#"><img src="<?php echo $this->basePath('assets/images/5000s-backtotop.png') ?>" alt="" title="Back to Top">Back to Top</a></p> -->
                <p class="text-muted">&copy; <?php echo sprintf($this->translate('2012 - %s Knowing Buddha Organization'), date('Y')) ?></p>
            </div>
        </footer>
		
	<!-- Inline JavaScript -->		
        <?php echo $this->inlineScript() ?>

	<!-- Bootstrap core JavaScript
	==================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <?php echo $this->headScript()
            ->offsetSetFile(1, $this->basePath('assets/jquery/2.1.4/jquery.min.js'))
            ->offsetSetFile(2, $this->basePath('assets/jquery-ui/1.11.4/jquery-ui.min.js'))
            ->offsetSetFile(3, $this->basePath('assets/bootstrap/3.3.6/js/bootstrap.min.js'))
            ->offsetSetFile(101, $this->basePath('assets/html5shiv/3.7.3/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->offsetSetFile(102, $this->basePath('assets/respond/1.4.2/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))                
        ?>
		
    </body>
</html>
