<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %s5000s.org Magazine%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('We are currently running Zend Framework version <a href="">%s</a>.'), \Zend\Version\Version::VERSION) ?></p>
</div>

<div class="row">
    <div class="col-xs-6 col-sm-4">
        <div class="thumbnail">
            <img src="<?php echo $this->basePath('assets/images/issue-10/01-cover.jpg') ?>" alt="" title="<?php echo $this->translate('ISSUE 10: NOV-DEC 2015') ?>">
            <div class="caption">
                <h3 class='label-success'><?php echo $this->translate('ISSUE 10: NOV-DEC 2015') ?></h3>              
                <p><a class="btn btn-success" role="button" href="#"><?php echo $this->translate('Membership') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
    <div class="col-xs-6 col-sm-4">
        <div class="thumbnail">
            <img src="<?php echo $this->basePath('assets/images/issue-09/01-cover.jpg') ?>" alt="" title="<?php echo $this->translate('ISSUE 9: SEP-OCT 2015') ?>">
            <div class="caption">
                <h3 class='label-success'><?php echo $this->translate('ISSUE 9: SEP-OCT 2015') ?></h3>              
                <p><a class="btn btn-success" role="button" href="#"><?php echo $this->translate('Membership') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
    <div class="col-xs-6 col-sm-4">
        <div class="thumbnail">
            <img src="<?php echo $this->basePath('assets/images/issue-08/01-cover.jpg') ?>" alt="" title="<?php echo $this->translate('ISSUE 8 - JUL-AUG 2015') ?>">
            <div class="caption">
                <h3 class='label-success'><?php echo $this->translate('ISSUE 8 - JUL-AUG 2015') ?></h3>              
                <p><a class="btn btn-success" role="button" href="#"><?php echo $this->translate('Membership') ?> &raquo;</a></p>
            </div>
        </div>        
    </div>
</div>
<div class="row">
    <div class="col-xs-6 col-sm-4">
        <div class="thumbnail">
            <img src="<?php echo $this->basePath('assets/images/issue-vesak2015/01-cover.jpg') ?>" alt="" title="<?php echo $this->translate('Extra Issue for Vesak Day') ?>">
            <div class="caption">
                <h3 class='label-success'><?php echo $this->translate('Extra Issue for Vesak Day') ?></h3>              
                <p><a class="btn btn-success" role="button" href="#"><?php echo $this->translate('Membership') ?> &raquo;</a></p>
            </div>
        </div>        
    </div>    
    <div class="col-xs-6 col-sm-4">
        <div class="thumbnail">
            <img src="<?php echo $this->basePath('assets/images/issue-vesak2015/01-cover.jpg') ?>" alt="" title="<?php echo $this->translate('ISSUE 7 - MAR-APR 2015') ?>">
            <div class="caption">
                <h3 class='label-success'><?php echo $this->translate('ISSUE 7 - MAR-APR 2015') ?></h3>              
                <p><a class="btn btn-success" role="button" href="#"><?php echo $this->translate('Membership') ?> &raquo;</a></p>
            </div>
        </div>        
    </div>
    <div class="col-xs-6 col-sm-4">
        <div class="thumbnail">
            <img src="<?php echo $this->basePath('assets/images/issue-vesak2015/01-cover.jpg') ?>" alt="" title="<?php echo $this->translate('ISSUE 6 - JAN-FEB 2015') ?>">
            <div class="caption">
                <h3 class='label-success'><?php echo $this->translate('ISSUE 6 - JAN-FEB 2015') ?></h3>              
                <p><a class="btn btn-success" role="button" href="#"><?php echo $this->translate('Membership') ?> &raquo;</a></p>
            </div>
        </div>        
    </div>
</div>
<div class="row">
    <div class="col-xs-6 col-sm-4">
        <div class="thumbnail">
            <img src="<?php echo $this->basePath('assets/images/issue-vesak2015/01-cover.jpg') ?>" alt="" title="<?php echo $this->translate('ISSUE 5 - NOV-DEC 2014') ?>">
            <div class="caption">
                <h3 class='label-success'><?php echo $this->translate('ISSUE 5 - NOV-DEC 2014') ?></h3>              
                <p><a class="btn btn-success" role="button" href="#"><?php echo $this->translate('Membership') ?> &raquo;</a></p>
            </div>
        </div>        
    </div>
    <div class="col-xs-6 col-sm-4">
        <div class="thumbnail">
            <img src="<?php echo $this->basePath('assets/images/issue-vesak2015/01-cover.jpg') ?>" alt="" title="<?php echo $this->translate('ISSUE 4 - SEP-OCT 2014') ?>">
            <div class="caption">
                <h3 class='label-success'><?php echo $this->translate('ISSUE 4 - SEP-OCT 2014') ?></h3>              
                <p><a class="btn btn-success" role="button" href="#"><?php echo $this->translate('Membership') ?> &raquo;</a></p>
            </div>
        </div>        
    </div>
    <div class="col-xs-6 col-sm-4">
        <div class="thumbnail">
            <img src="<?php echo $this->basePath('assets/images/issue-vesak2015/01-cover.jpg') ?>" alt="" title="<?php echo $this->translate('ISSUE 3 - JUL-AUG 2014') ?>">
            <div class="caption">
                <h3 class='label-success'><?php echo $this->translate('ISSUE 3 - JUL-AUG 2014') ?></h3>              
                <p><a class="btn btn-success" role="button" href="#"><?php echo $this->translate('Membership') ?> &raquo;</a></p>
            </div>
        </div>         
    </div>
</div>    
<div class="row">    
    <div class="col-xs-6 col-sm-4">
        <div class="thumbnail">
            <img src="<?php echo $this->basePath('assets/images/issue-vesak2015/01-cover.jpg') ?>" alt="" title="<?php echo $this->translate('ISSUE 2 - MAR-APR 2014') ?>">
            <div class="caption">
                <h3 class='label-success'><?php echo $this->translate('ISSUE 2 - MAR-APR 2014') ?></h3>              
                <p><a class="btn btn-success" role="button" href="#"><?php echo $this->translate('Membership') ?> &raquo;</a></p>
            </div>
        </div>        
    </div>
    <div class="col-xs-6 col-sm-4">
        <div class="thumbnail">
            <img src="<?php echo $this->basePath('assets/images/issue-vesak2015/01-cover.jpg') ?>" alt="" title="<?php echo $this->translate('ISSUE 1 - JAN-FEB 2014') ?>">
            <div class="caption">
                <h3 class='label-success'><?php echo $this->translate('ISSUE 1 - JAN-FEB 2014') ?></h3>              
                <p><a class="btn btn-success" role="button" href="#"><?php echo $this->translate('Membership') ?> &raquo;</a></p>
            </div>
        </div>        
    </div>
</div>
