<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sMagazinePro%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('MagazinePro Membership Application.<br/>We are currently running Zend Framework version <a href="">%s</a>.'), \Zend\Version\Version::VERSION) ?></p>
</div>

<div class="row">

    <div class="col-xs-6 col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Issue 1 - JAN-FEB 2014</h3>
            </div>
            <div class="panel-body">
                <p></p>
                <p><a class="btn btn-success pull-right" href="">Membership &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-xs-6 col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Issue 2 - MAR-APR 2014</h3>
            </div>
            <div class="panel-body">
                <p></p>
                <p><a class="btn btn-success pull-right" href="">Membership &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-xs-6 col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Issue 3 - JUL-AUG 2014</h3>
            </div>
            <div class="panel-body">
                <p></p>
                <p><a class="btn btn-success pull-right" href="">Membership &raquo;</a></p>
            </div>
        </div>
    </div>
    
    <div class="col-xs-6 col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Issue 4 - SEP-OCT 2014</h3>
            </div>
            <div class="panel-body">
                <p></p>
                <p><a class="btn btn-success pull-right" href="">Membership &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-xs-6 col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Issue 5 - NOV-DEC 2014</h3>
            </div>
            <div class="panel-body">
                <p></p>
                <p><a class="btn btn-success pull-right" href="">Membership &raquo;</a></p>
            </div>
        </div>
    </div>    
</div>

<div class="row">

    <div class="col-xs-6 col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Issue 6 - JAN-FEB 2015</h3>
            </div>
            <div class="panel-body">
                <p></p>
                <p><a class="btn btn-success pull-right" href="">Membership &raquo;</a></p>
            </div>
        </div>
    </div>
    
    <div class="col-xs-6 col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Issue 7 - MAR-APR 2015</h3>
            </div>
            <div class="panel-body">
                <p></p>
                <p><a class="btn btn-success pull-right" href="">Membership &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-xs-6 col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Issue 8 - JUL-AUG 2015</h3>
            </div>
            <div class="panel-body">
                <p></p>
                <p><a class="btn btn-success pull-right" href="">Membership &raquo;</a></p>
            </div>
        </div>
    </div>
    
    <div class="col-xs-6 col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Issue 9 - SEP-OCT 2015</h3>
            </div>
            <div class="panel-body">
                <p></p>
                <p><a class="btn btn-success pull-right" href="">Membership &raquo;</a></p>
            </div>
        </div>
    </div>
    
    <div class="col-xs-6 col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Issue 10 - NOV-DEC 2015</h3>
            </div>
            <div class="panel-body">
                <p></p>
                <p><a class="btn btn-success pull-right" href="">Membership &raquo;</a></p>
            </div>
        </div>
    </div>    
</div>