<div class="thumbnail-borderless">
    <img class="img-responsive" src="<?php echo $this->basePath('assets/images/5000s-header.png') ?>" alt="" title="<?php echo $this->translate('5000s Header') ?>">
</div>

<h3 class="text-center"><span class="glyphicon glyphicon-book theme-color"></span> Magazine Issued 2015</h3>

<div class="row">
    <div class="col-sm-6 col-md-4 col-lg-3">
        <div class="thumbnail">
            <img src="<?php echo $this->basePath('assets/images/issue-10/01-cover.jpg') ?>" alt="" title="<?php echo $this->translate('ISSUE 10: NOV-DEC 2015') ?>">            
            <div class="caption">
                <button type="button" class="btn btn-success btn-block">
                    <span class="badge">10</span>&nbsp;<?php echo $this->translate('NOV-DEC 2015') ?>
                </button>
            </div>
        </div>            
    </div>
    <div class="col-sm-6 col-md-4 col-lg-3">
        <div class="thumbnail">
            <img src="<?php echo $this->basePath('assets/images/issue-09/01-cover.jpg') ?>" alt="" title="<?php echo $this->translate('ISSUE 9: SEP-OCT 2015') ?>">
            <div class="caption">
                <button type="button" class="btn btn-success btn-block">
                    <span class="badge">9</span>&nbsp;<?php echo $this->translate('SEP-OCT 2015') ?>
                </button>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-4 col-lg-3">
        <div class="thumbnail">
            <img src="<?php echo $this->basePath('assets/images/issue-08/01-cover.jpg') ?>" alt="" title="<?php echo $this->translate('ISSUE 8: JUL-AUG 2015') ?>">
            <div class="caption">
                <button type="button" class="btn btn-success btn-block">
                    <span class="badge">8</span>&nbsp;<?php echo $this->translate('JUL-AUG 2015') ?>
                </button>
            </div>
        </div>            
    </div>
    <div class="col-sm-6 col-md-4 col-lg-3">
        <div class="thumbnail">
            <img src="<?php echo $this->basePath('assets/images/issue-vesak2015/01-cover.jpg') ?>" alt="" title="<?php echo $this->translate('EXTRA: VESAK DAY') ?>">
            <div class="caption">
                <button type="button" class="btn btn-success btn-block">
                    <span class="badge">EX</span>&nbsp;<?php echo $this->translate('VESAK DAY') ?>
                </button>
            </div>
        </div>            
    </div>
    <div class="col-sm-6 col-md-4 col-lg-3">
        <div class="thumbnail">
            <img src="<?php echo $this->basePath('assets/images/issue-07/01-cover.jpg') ?>" alt="" title="<?php echo $this->translate('ISSUE 7: MAR-APR 2015') ?>">
            <div class="caption">
                <button type="button" class="btn btn-success btn-block">
                    <span class="badge">7</span>&nbsp;<?php echo $this->translate('MAR-APR 2015') ?>
                </button>
            </div>
        </div>            
    </div>
    <div class="col-sm-6 col-md-4 col-lg-3">
        <div class="thumbnail">
            <img src="<?php echo $this->basePath('assets/images/issue-06/01-cover.jpg') ?>" alt="" title="<?php echo $this->translate('ISSUE 6: JAN-FEB 2015') ?>">
            <div class="caption">
                <button type="button" class="btn btn-success btn-block">
                    <span class="badge">6</span>&nbsp;<?php echo $this->translate('JAN-FEB 2015') ?>
                </button>
            </div>
        </div>            
    </div>   
</div>

<h3 class="text-center"><span class="glyphicon glyphicon-book theme-color"></span> Magazine Issued 2014</h3>

<div class="row">   
    <div class="col-sm-6 col-md-4 col-lg-3">
        <div class="thumbnail">
            <img src="<?php echo $this->basePath('assets/images/issue-05/01-cover.jpg') ?>" alt="" title="<?php echo $this->translate('ISSUE 5: NOV-DEC 2014') ?>">
            <div class="caption">
                <button type="button" class="btn btn-success btn-block">
                    <span class="badge">5</span>&nbsp;<?php echo $this->translate('NOV-DEC 2014') ?>
                </button>
            </div>
        </div>            
    </div>
    <div class="col-sm-6 col-md-4 col-lg-3">
        <div class="thumbnail">
            <img src="<?php echo $this->basePath('assets/images/issue-04/01-cover.jpg') ?>" alt="" title="<?php echo $this->translate('ISSUE 4: SEP-OCT 2014') ?>">
            <div class="caption">
                <button type="button" class="btn btn-success btn-block">
                    <span class="badge">4</span>&nbsp;<?php echo $this->translate('SEP-OCT 2014') ?>
                </button>
            </div>
        </div>            
    </div>
    <div class="col-sm-6 col-md-4 col-lg-3">
        <div class="thumbnail">
            <img src="<?php echo $this->basePath('assets/images/issue-03/01-cover.jpg') ?>" alt="" title="<?php echo $this->translate('ISSUE 3: JUL-AUG 2014') ?>">
            <div class="caption">
                <button type="button" class="btn btn-success btn-block">
                    <span class="badge">3</span>&nbsp;<?php echo $this->translate('JUL-AUG 2014') ?>
                </button>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-4 col-lg-3">
        <div class="thumbnail">
            <img src="<?php echo $this->basePath('assets/images/issue-02/01-cover.jpg') ?>" alt="" title="<?php echo $this->translate('ISSUE 2: MAR-APR 2014') ?>">
            <div class="caption">
                <button type="button" class="btn btn-success btn-block">
                    <span class="badge">2</span>&nbsp;<?php echo $this->translate('MAR-APR 2014') ?></span>
                </button>
            </div>
        </div>            
    </div>  
    <div class="col-sm-6 col-md-4 col-lg-3">
        <div class="thumbnail">
            <img src="<?php echo $this->basePath('assets/images/issue-01/01-cover.jpg') ?>" alt="" title="<?php echo $this->translate('ISSUE 1: JAN-FEB 2014') ?>">
            <div class="caption">
                <!--
                <button type="button" class="btn btn-success btn-block">
                    <span class="badge">1</span>&nbsp;<?php echo $this->translate('JAN-FEB 2014') ?></span>
                </button>
                -->
                <p><span class="badge">1</span>&nbsp;<?php echo $this->translate('JAN-FEB 2014') ?></span></p>
            </div>
        </div>            
    </div>
</div>
